SELECT
       RI.FOOD_TYPE
     , RI.REST_ID
     , RI.REST_NAME
     , RI.FAVORITES
  FROM REST_INFO RI
     , (SELECT
               FOOD_TYPE
             , MAX(FAVORITES) MAX_FAVORITES
          FROM REST_INFO
         WHERE 1=1
        GROUP BY FOOD_TYPE) SUB_MAX
 WHERE 1=1
   AND RI.FOOD_TYPE = SUB_MAX.FOOD_TYPE
   ANd RI.FAVORITES = SUB_MAX.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;
   