SELECT 
       BOOK.CATEGORY, SUM(SUB.SALES) AS TOTAL_SALES
  FROM BOOK
     , (SELECT 
               *
          FROM BOOK_SALES
         WHERE 1=1
           AND SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD')
                              AND TO_DATE('2022-01-31', 'YYYY-MM-DD')) SUB
  WHERE BOOK.BOOK_ID = SUB.BOOK_ID
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY


                      